spring:
  application:
    name: userservice
  config:
    import: ${SPRING_CONFIG_IMPORT:optional:configserver:http://localhost:8071}
  profiles:
    active: dev
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    properties:
      security.protocol: PLAINTEXT
    topic:
      name: optMail
    bootstrap-servers: ${SPRING_URL_KAFKA:localhost:9092}
  redis:
    host: ${SPRING_REDIS_HOST:127.0.0.1}
    port: ${SPRING_REDIS_PORT:6379}
server:
  port: 9000