apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: dishservice
  name: dishservice
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: dishservice
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    metadata:
      labels:
        io.kompose.service: dishservice
    spec:
      containers:
        - env:
            - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
              value: http://eurekaservice:8070/eureka/
            - name: SPRING_CONFIG_IMPORT
              value: configserver:http://configserver:8071
            - name: SPRING_DATASOURCE_PASSWORD
              value: root
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysqlservice:3306/HuongDichVu?allowPublicKeyRetrieval=true&useSSL=false
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_ZIPKIN_BASE_URL
              value: http://zipkin:9411/api/v2/spans
          image: doctorhoai/huongdichvu_dishservice:f17
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: 512Mi
              cpu: 200m
            limits:
              memory: 1024Mi
              cpu: 1000m
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8083
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8083
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
          name: dishservice
          ports:
            - containerPort: 8083
              protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: dishservice
  name: dishservice
spec:
  ports:
    - name: "8083"
      port: 8083
      targetPort: 8083
  sessionAffinity: None
  selector:
    io.kompose.service: dishservice
