apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: apigateway
  name: apigateway
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: apigateway
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        io.kompose.service: apigateway
    spec:
      containers:
        - env:
            - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
              value: http://eurekaservice:8070/eureka/
            - name: EUREKA_INSTANCE
              value: eureka
            - name: SPRING_CONFIG_IMPORT
              value: configserver:http://configserver:8071
            - name: SPRING_ZIPKIN_BASE_URL
              value: http://zipkin:9411/api/v2/spans
          image: doctorhoai/huongdichvu_apigateway:f3
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: 512Mi
              cpu: 100m
            limits:
              memory: 1024Mi
              cpu: 500m
          livenessProbe:
            exec:
              command:
                - curl --fail --silent http://localhost:6380/actuator/healthy/readiness | grep UP || exit 1
            failureThreshold: 20
            initialDelaySeconds: 10
            periodSeconds: 20
            timeoutSeconds: 5
          name: apigateway
          ports:
            - containerPort: 6380
              protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: apigateway
  name: apigateway
spec:
  type: LoadBalancer
  ports:
    - name: "6380"
      port: 6380
      targetPort: 6380
  sessionAffinity: None
  selector:
    io.kompose.service: apigateway
