apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: proxyclient
  name: proxyclient
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: proxyclient
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        io.kompose.service: proxyclient
    spec:
      containers:
        - name: proxyclient
          image: doctorhoai/huongdichvu_proxyservice:f17
          imagePullPolicy: IfNotPresent
          env:
            - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
              value: http://eurekaservice:8070/eureka/
            - name: EUREKA_INSTANCE
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "true"
            - name: SPRING_CONFIG_IMPORT
              value: configserver:http://configserver:8071
            - name: SPRING_DATASOURCE_PASSWORD
              value: root
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysqlservice:3306/HuongDichVu?allowPublicKeyRetrieval=true&useSSL=false
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_REDIS_HOST
              value: redis
            - name: SPRING_REDIS_PORT
              value: "6379"
            - name: SPRING_ZIPKIN_BASE_URL
              value: http://zipkin:9411/api/v2/spans
            - name: SPRING_CLIENT_ID_GITHUB
              value: Ov23liwafWo0cDS2xWMe
            - name: SPRING_CLIENT_SECRET_GITHUB
              value: 13cbbb85dc169c670a08bed400eb07441f5baae9
            - name: SPRING_REDIRECT_URI_GITHUB
              value: http://localhost:6380/login/oauth2/code/{registrationId}
            - name: SPRING_REDIRECT_OAUTH
              value: http://localhost:5173/oauth2/redirect
          ports:
            - containerPort: 8888
              protocol: TCP
          resources:
            requests:
              memory: 512Mi
              cpu: 200m
            limits:
              memory: 1024Mi
              cpu: 1000m
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8888
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8888
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: proxyclient
  name: proxyclient
spec:
  type: LoadBalancer
  ports:
    - name: "8888"
      port: 8888
      targetPort: 8888
  sessionAffinity: ClientIP
  selector:
    io.kompose.service: proxyclient
