apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml -o k8s/
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: apigateway
  name: apigateway
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: apigateway
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml -o k8s/
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: apigateway
    spec:
      containers:
        - env:
            - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
              value: http://eurekaservice:8070/eureka/
            - name: EUREKA_INSTANCE
              value: eureka
            - name: SPRING_CONFIG_IMPORT
              value: configserver:http://configserver:8071
            - name: SPRING_ZIPKIN_BASE_URL
              value: http://zipkin:9411/api/v2/spans
          image: doctorhoai/huongdichvu_apigateway:f3
          livenessProbe:
            exec:
              command:
                - curl --fail --silent http://localhost:6380/actuator/healthy/readiness | grep UP || exit 1
            failureThreshold: 20
            initialDelaySeconds: 10
            periodSeconds: 20
            timeoutSeconds: 5
          name: apigateway
          ports:
            - containerPort: 6380
              protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: apigateway
  name: apigateway
spec:
  ports:
    - name: "6380"
      port: 6380
      targetPort: 6380
  selector:
    io.kompose.service: apigateway
