apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: scale-container
  namespace: default
spec:
  maxReplicas: 3
  metrics:
    - resource:
        name: cpu
        target:
          averageUtilization: 10
          type: Utilization
      type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: apigateway
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 5
