spring:
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
      httpclient:
        connect-timeout: 2000
        response-timeout: 10s
resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 2
      failureRateThreshold: 50
      waitDurationInOpenState: 10000

resilience4j.ratelimiter:
  configs:
    default:
      timeoutDuration: 1000
      limitRefreshPeriod: 5000
      limitForPeriod: 1

resilience4j.retry:
  configs:
    default:
      max-attempts: 3
      wait-duration: 50
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 2
      ignoreExceptions:
        - java.lang.NullPointerException
      retryExceptions:
        - java.util.concurrent.TimeoutException
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8070/eureka/
    register-with-eureka: true
    fetch-registry: true
management:
  tracing:
    sampling:
      probability: 1.0
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true

info:
  app:
    name: "Api gateway service"
    description: "Using fetch about Api gatewau"
    version: "1.0.0"
server:
  port: 6379
logging:
  pattern:
    level: DEBUG

pattern:
  level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"
