#spring:
#  zipkin:
#    enabled: true
#    baseUrl: ${SPRING_ZIPKIN_BASE_URL:http://localhost:9411/api/v2/spans}
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          lower-case-service-id: true
#      httpclient:
#        connect-timeout: 10000
#        response-timeout: 30s
#      globalcors:
#        corsConfigurations:
#          '[/**]':
#            allowedOrigins: ${SPRING_CQRS_URL:http://localhost:5173}
#            allowedMethods: "*"
#            allowedHeaders: "*"
#            allowCredentials: true
#resilience4j.circuitbreaker:
#  instances:
#    proxySupport:
#      sliding-window-size: 10  # Giám sát 10 request gần nhất
#      failure-rate-threshold: 50  # Chỉ kích hoạt khi 50% request bị lỗi
#      slow-call-rate-threshold: 75  # Kích hoạt nếu 75% request quá chậm
#      slow-call-duration-threshold: 10000ms  # Chờ tối đa 5 giây trước khi coi là chậm
#      wait-duration-in-open-state: 30s  # Đợi 10 giây trước khi thử lại
#
#resilience4j.ratelimiter:
#  configs:
#    default:
#      timeoutDuration: 10000
#      limitRefreshPeriod: 10000
#      limitForPeriod: 10
#
#resilience4j.retry:
#  configs:
#    default:
#      max-attempts: 3
#      wait-duration: 5000
#      enableExponentialBackoff: true
#      exponentialBackoffMultiplier: 2
#      ignoreExceptions:
#        - java.lang.NullPointerException
#      retryExceptions:
#        - java.util.concurrent.TimeoutException
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    service-url:
#      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8070/eureka/}
#    register-with-eureka: true
#    fetch-registry: true
#management:
#  tracing:
#    sampling:
#      probability: 1.0
#  zipkin:
#    tracing:
#      endpoint: ${SPRING_ZIPKIN_BASE_URL:http://localhost:9411/api/v2/spans}
#  health:
#    livenessstate:
#      enabled: true
#    readinessstate:
#      enabled: true
#    circuitbreakers:
#      enabled: true
#  endpoint:
#    gateway:
#      enabled: true
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#  info:
#    env:
#      enabled: true
#
#info:
#  app:
#    name: "Api gateway service"
#    description: "Using fetch about Api gateway"
#    version: "1.0.0"
#server:
#  port: 6380
#logging:
#  pattern:
#    level: DEBUG
#
#pattern:
#  level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"
