eureka:
  instance:
    hostname: ${EUREKA_INSTANCE:localhost}
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      default: http://${eureka.instance.hostname}:${server.port}/eureka/

server:
  port: 8070
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      enpoint: ${SPRING_ZIPKIN_BASE_URL:http://localhost:9411/}
  endpoint:
    web:
      exposure:
        include: "*"
    health:
      probes:
        enabled: true
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
    circuitbreakers:
      enabled: true
pattern:
  level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"