spring:
  application:
    name: paymentservice
  config:
    import: ${SPRING_CONFIG_IMPORT:optional:configserver:http://localhost:8071}
  profiles:
    active: dev
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    properties:
      security.protocol: PLAINTEXT
    topic:
      name: ticket
    bootstrap-servers: ${SPRING_URL_KAFKA:localhost:9092}
  dinary:
    cloud:
      name: ${DINARY_CLOUD_NAME:de8nxh0wc}
    api:
      key: ${DINARY_API_KEY:878329439565671}
      secret: ${DINARY_API_SECRET:BUu5E2lxTuE8q9233XjxCm_ok4g}
  servlet:
    multipart:
      max-file-size: 2GB
      max-request-size: 2GB
apikey : ${STRIPE_KEY:sk_test_51QuPM5BcNft3NmLQIaQ2LrDY86NNOoBnFpaNysptacRccKpa0S2zkyXDg8a7EhPUDCvu1ylbwBjWcD0K7YaFQNoN00ZGbBZc0L}