spring:
  application:
    name: notificationservice
  mail:
    host: smtp.gmail.com
    port: 587
    username: dpquochoai@gmail.com
    password: haas dmfz dscz ppgi
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      bootstrap-servers: ${SPRING_URL_KAFKA:localhost:9092}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"
    topic:
      name: ticket
  dinary:
    cloud:
      name: ${DINARY_CLOUD_NAME:de8nxh0wc}
    api:
      key: ${DINARY_API_KEY:878329439565671}
      secret: ${DINARY_API_SECRET:BUu5E2lxTuE8q9233XjxCm_ok4g}
  servlet:
    multipart:
      max-file-size: 2GB
      max-request-size: 2GB